postgres_cfg:
  host: postgres
  port: 5432
  user: postgres
  password: postgres
  database: postgres
  table_name: image_metadata
  connection_uri: postgresql+psycopg2://${postgres_cfg.user}:${postgres_cfg.password}@${postgres_cfg.host}:${postgres_cfg.port}/${postgres_cfg.database}

minio_cfg:
  endpoint: http://minio:9000
  bucket: unlabeled-images
  prefix: ""

thumbnails_path: s3://unlabeled-images/run_dir/thumbnails
output_path: s3://unlabeled-images/run_dir/output