services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  prefect-server:
    image: prefecthq/prefect:3-python3.12
    restart: unless-stopped
    command: [ "prefect", "server", "start", "--host", "0.0.0.0" ]
    ports:
      - "4200:4200"
